name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x 

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -o build

      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v3
        with:
          repository: mrpeje/mrpeje.github.io
          path: ./mrpeje.github.io

      - name: Copy built Blazor app to GitHub Pages repo
        run: |
          cp -r ./bin/Release/net6.0/browser-wasm/publish/* ./mrpeje.github.io  

      - name: Authenticate and push to GitHub Pages
        run: |
          cd ./gh-pages-repo
          git init
          git remote add origin https://mrpeje:${{ secrets.DEPLOYTOKEN }}@github.com/mrpeje/mrpeje.github.io.git
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add .
          git commit -m "Deploy Blazor App to GitHub Pages"
          git push origin main --force
